name: Deploy Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Tag Commit
        if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'deploy') }}
        run: echo "${{ github }}"

      - name: Calculate tag
        id: calculate-tag
        if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'deploy') }}
        run: echo "NEW_TAG=v0.0.1" >> "$GITHUB_OUTPUT"

      - name: Tag Commit
        if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'deploy') }}
        run: git tag ${{ steps.calculate-tag.outputs.NEW_TAG }}

      - name: Push Tag
        if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'deploy') }}
        run: git push --tags
