name: Deploy Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run on master and deploy branches
        if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'deploy') }}
        run: |
          git tag v0.0.1

      - name: Run on master and deploy branches
        if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'deploy') }}
        run: |
          git push --tags
